version: '3.8'

services:
  portainer:
    image: cr.portainer.io/portainer/portainer-ce:latest
    container_name: test
    restart: always
    ports:
      -"8000:8000"
      -"9000:9000"
    volumes:
      -/var/run/docker.sock:/var/run/docker.sock
      -portainer_data:/data

volumes:
  portainer_data:
